### ISSUE TITLE
QA - [PROD] office of vice president misisng images in prod environment

### ISSUE THREAD

**Issue by Miraii133** [SAMAHAN-Systems-Development/samahan-all-for-more-frontend#129]
Issue:
![image](https://github.com/user-attachments/assets/55cdc770-17bc-47e2-bdfc-fd540bd7819e)

Status:
dev environment shows image but not in prod 
![image](https://github.com/user-attachments/assets/672c658d-0fd1-4ba4-b2b1-e3c4e0fc5f89)

Should be:
Have images

**Comment by rhaeyx** [comment]
Issue was with a filename mismatch, capitalization sa filenames lang. Deploying a fix now.

**Comment by rhaeyx** [comment]
Should be good now. Pa reopen nalng if the issue persists.

**Comment by Miraii133** [comment]
![image](https://github.com/user-attachments/assets/e5a91f8d-3a07-4bf8-aacb-a318b3a1e597)
