### ISSUE TITLE
QA - office of the treasurer claire's card is blurry upscale image

### ISSUE THREAD

**Issue by Miraii133** [SAMAHAN-Systems-Development/samahan-all-for-more-frontend#162]
Issue:
![image](https://github.com/user-attachments/assets/32dc1c51-f783-4c6f-8a3b-779363094353)
Very blurry image

Should be:
Not blurry image

**Comment by shunindesuuu** [comment]
upscaled as much as possible for some reason still blurry

**Comment by shunindesuuu** [comment]
joke naa koy nadiscover na wow
