### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by shunindesuuu** [SAMAHAN-Systems-Development/samahan-all-for-more-frontend#5]
Banner component

Note:
- For animation for the balls, use the provided component (Spheres)
- Image should be props so that it can be changed based on its usage on different page/s

For further questions, contact me (Paolo) or our UI/UX Head, Mav.
![image](https://github.com/user-attachments/assets/81fbe451-49b9-4db1-8db3-4fed3116813f)

**Comment by GuyWithBag** [comment]
Desktop done, Awaiting mobile ui/ux

**Comment by shunindesuuu** [comment]
@GuyWithBag Hello! updated the description para clear. Sorry for this if late na huhu

**Comment by shunindesuuu** [comment]
@GuyWithBag Hello, my mistake again for not seeing this, but can you make the title of the banner changeable? yung "Banner Layout" na text. thank you!

**Comment by GuyWithBag** [comment]
> @GuyWithBag Hello, my mistake again for not seeing this, but can you make the title of the banner changeable? yung "Banner Layout" na text. thank you!

I think changeable na po siya sa BannerImage component
