### ISSUE TITLE
Event Finder Modal

### ISSUE THREAD

**Issue by shunindesuuu** [SAMAHAN-Systems-Development/samahan-all-for-more-frontend#56]
### **Event Finder Modal (Refer to Figma for the full look)**
Located at `Paolo Ready` in Figma

To be used in the Event Finder Page where it will be the pop-up modal when the 'View Details' button is clicked and uses react-query to fetch data for display of the clicked event.

#### API Integration: Use `react-query` from tanstack to fetch data
- Event Data: GET /api/events

#### Data to Display: 
**Event Fields** (from /api/events):
- `name`: The name of the event.
- `location_id`: `location`
- `description`
- `start_time`: Event start time (formatted appropriately ex. "2028-10-15T09:00:00Z").
- `end_time`: Event end time (formatted appropriately).
- `registration_link`
- `poster_images`: Array of poster images

### **REMINDERS**

- Kindly use what is set in the tailwind config for the text sizes for **consistency**. Check the `tailwind.config.ts` and look for the fontSize section of the config. 

- For the spacing, margin, and etc, you don't have to make it a 1:1 copy from Figma to Code, adjust it if you feel like it is better or if it is right to you. 

![image](https://github.com/user-attachments/assets/81a8eb5c-1944-4553-ae32-1b86c32f7288)

**Comment by GuyWithBag** [comment]
I have to un assign myself this since my schedule this week is flooded.
